/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.Controller;
import javax.swing.BorderFactory;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JSlider;
import javax.swing.JTabbedPane;
import javax.swing.JToggleButton;

/**
 *
 * @author Tommy
 */
public class LaysHistView extends javax.swing.JDialog {
    private DefaultListModel mlayers;
    private DefaultListModel mhistory;
    private MainView mainview;
    private Controller control;

    /**
     * Creates new form LaysHistView
     */
    public LaysHistView(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        this.setVisible(false);
        this.setTitle("Layers - History - MyPhotoshop");
        mainview = (MainView)parent;
        control = mainview.getController();
        LIlayers.addListSelectionListener(control);
        LIhistory.addListSelectionListener(control);
        BlaysRemove.addActionListener(control);
        BlaysUp.addActionListener(control);
        BlaysDown.addActionListener(control);
        mlayers = new DefaultListModel();
        LIlayers.setCellRenderer(new MyCellRendered());
        LIlayers.setModel(mlayers);
        mhistory = new DefaultListModel();
        LIhistory.setCellRenderer(new MyCellRendered());
        LIhistory.setModel(mhistory);
        BlaysUp.setIcon(new ImageIcon("src/images/up.png"));
        BlaysDown.setIcon(new ImageIcon("src/images/down.png"));
        BlaysRemove.setIcon(new ImageIcon("src/images/remove.png"));
        BlaysMergeUp.addActionListener(control);
        BlaysMergeUp.setIcon(new ImageIcon("src/images/mergeup.png"));
        BlaysMergeDown.addActionListener(control);
        BlaysMergeDown.setIcon(new ImageIcon("src/images/mergedown.png"));
        TBlaysView.addActionListener(control);
        TBlaysView.setIcon(new ImageIcon("src/images/eye.png"));
        TBlaysView.setSelectedIcon(new ImageIcon("src/images/eyebis.png"));
        SLlaysAlpha.addChangeListener(control);
        BlaysRename.addActionListener(control);
    }
    
    public JSlider getSLlaysAlpha() {
        return SLlaysAlpha;
    }
    
    public JLabel getLlaysAlpha() {
        return LlaysAlpha;
    }
    
    public JButton getBlaysRename() {
        return BlaysRename;
    }
    
    public DefaultListModel getModelLayers() {
        return mlayers;
    }
    
    public DefaultListModel getModelHistory() {
        return mhistory;
    }
    
    public JList getLIlayers() {
        return LIlayers;
    }
    
    public JList getLIhistory() {
        return LIhistory;
    }
    
    public JButton getBlaysMergeUp() {
        return BlaysMergeUp;
    }
    
    public JButton getBlaysMergeDown() {
        return BlaysMergeDown;
    }
    
    public JButton getBlaysRemove() {
        return BlaysRemove;
    }
    
    public JToggleButton getBlaysView() {
        return TBlaysView;
    }
    
    public JButton getBlaysUp() {
        return BlaysUp;
    }
    
    public JButton getBlaysDown() {
        return BlaysDown;
    }
    
    public JTabbedPane getTPlayshist() {
        return TPlayshist;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Playshist = new javax.swing.JPanel();
        TPlayshist = new javax.swing.JTabbedPane();
        Players = new javax.swing.JPanel();
        SPlayers = new javax.swing.JScrollPane();
        LIlayers = new javax.swing.JList();
        BlaysRemove = new javax.swing.JButton();
        BlaysUp = new javax.swing.JButton();
        BlaysDown = new javax.swing.JButton();
        BlaysMergeUp = new javax.swing.JButton();
        BlaysMergeDown = new javax.swing.JButton();
        TBlaysView = new javax.swing.JToggleButton();
        SLlaysAlpha = new javax.swing.JSlider();
        LlaysAlpha = new javax.swing.JLabel();
        BlaysRename = new javax.swing.JButton();
        Phistory = new javax.swing.JPanel();
        SPhistory = new javax.swing.JScrollPane();
        LIhistory = new javax.swing.JList();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        TPlayshist.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        LIlayers.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        LIlayers.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        SPlayers.setViewportView(LIlayers);

        BlaysRemove.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        BlaysRemove.setMaximumSize(new java.awt.Dimension(29, 22));
        BlaysRemove.setMinimumSize(new java.awt.Dimension(29, 22));
        BlaysRemove.setPreferredSize(new java.awt.Dimension(29, 22));

        BlaysUp.setMaximumSize(new java.awt.Dimension(29, 22));
        BlaysUp.setMinimumSize(new java.awt.Dimension(29, 22));
        BlaysUp.setPreferredSize(new java.awt.Dimension(29, 22));

        BlaysDown.setMaximumSize(new java.awt.Dimension(29, 22));
        BlaysDown.setMinimumSize(new java.awt.Dimension(29, 22));
        BlaysDown.setPreferredSize(new java.awt.Dimension(29, 22));

        BlaysMergeUp.setMaximumSize(new java.awt.Dimension(29, 22));
        BlaysMergeUp.setMinimumSize(new java.awt.Dimension(29, 22));
        BlaysMergeUp.setPreferredSize(new java.awt.Dimension(29, 22));

        BlaysMergeDown.setMaximumSize(new java.awt.Dimension(29, 22));
        BlaysMergeDown.setMinimumSize(new java.awt.Dimension(29, 22));
        BlaysMergeDown.setPreferredSize(new java.awt.Dimension(29, 22));

        TBlaysView.setMaximumSize(new java.awt.Dimension(29, 22));
        TBlaysView.setMinimumSize(new java.awt.Dimension(29, 22));
        TBlaysView.setPreferredSize(new java.awt.Dimension(29, 22));

        SLlaysAlpha.setMinimum(1);
        SLlaysAlpha.setMaximumSize(new java.awt.Dimension(122, 26));
        SLlaysAlpha.setMinimumSize(new java.awt.Dimension(122, 25));
        SLlaysAlpha.setPreferredSize(new java.awt.Dimension(122, 26));

        LlaysAlpha.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        LlaysAlpha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LlaysAlpha.setText("100");
        LlaysAlpha.setMaximumSize(new java.awt.Dimension(26, 26));
        LlaysAlpha.setMinimumSize(new java.awt.Dimension(26, 26));
        LlaysAlpha.setPreferredSize(new java.awt.Dimension(26, 26));

        BlaysRename.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        BlaysRename.setForeground(new java.awt.Color(100, 100, 100));
        BlaysRename.setText("...");
        BlaysRename.setMaximumSize(new java.awt.Dimension(30, 26));
        BlaysRename.setMinimumSize(new java.awt.Dimension(30, 26));
        BlaysRename.setPreferredSize(new java.awt.Dimension(30, 26));

        javax.swing.GroupLayout PlayersLayout = new javax.swing.GroupLayout(Players);
        Players.setLayout(PlayersLayout);
        PlayersLayout.setHorizontalGroup(
            PlayersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SPlayers, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(PlayersLayout.createSequentialGroup()
                .addGroup(PlayersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PlayersLayout.createSequentialGroup()
                        .addComponent(BlaysRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TBlaysView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BlaysUp, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BlaysDown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BlaysMergeUp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BlaysMergeDown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PlayersLayout.createSequentialGroup()
                        .addComponent(SLlaysAlpha, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LlaysAlpha, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BlaysRename, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        PlayersLayout.setVerticalGroup(
            PlayersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PlayersLayout.createSequentialGroup()
                .addComponent(SPlayers, javax.swing.GroupLayout.DEFAULT_SIZE, 562, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PlayersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BlaysUp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BlaysDown, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BlaysRemove, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BlaysMergeUp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BlaysMergeDown, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TBlaysView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PlayersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(SLlaysAlpha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PlayersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(LlaysAlpha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BlaysRename, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        TPlayshist.addTab("Layers", Players);

        LIhistory.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        LIhistory.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        SPhistory.setViewportView(LIhistory);

        javax.swing.GroupLayout PhistoryLayout = new javax.swing.GroupLayout(Phistory);
        Phistory.setLayout(PhistoryLayout);
        PhistoryLayout.setHorizontalGroup(
            PhistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SPhistory, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
        );
        PhistoryLayout.setVerticalGroup(
            PhistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SPhistory, javax.swing.GroupLayout.DEFAULT_SIZE, 622, Short.MAX_VALUE)
        );

        TPlayshist.addTab("History", Phistory);

        javax.swing.GroupLayout PlayshistLayout = new javax.swing.GroupLayout(Playshist);
        Playshist.setLayout(PlayshistLayout);
        PlayshistLayout.setHorizontalGroup(
            PlayshistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TPlayshist)
        );
        PlayshistLayout.setVerticalGroup(
            PlayshistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TPlayshist)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Playshist, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Playshist, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LaysHistView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LaysHistView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LaysHistView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LaysHistView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                LaysHistView dialog = new LaysHistView(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BlaysDown;
    private javax.swing.JButton BlaysMergeDown;
    private javax.swing.JButton BlaysMergeUp;
    private javax.swing.JButton BlaysRemove;
    private javax.swing.JButton BlaysRename;
    private javax.swing.JButton BlaysUp;
    private javax.swing.JList LIhistory;
    private javax.swing.JList LIlayers;
    private javax.swing.JLabel LlaysAlpha;
    private javax.swing.JPanel Phistory;
    private javax.swing.JPanel Players;
    private javax.swing.JPanel Playshist;
    private javax.swing.JSlider SLlaysAlpha;
    private javax.swing.JScrollPane SPhistory;
    private javax.swing.JScrollPane SPlayers;
    private javax.swing.JToggleButton TBlaysView;
    private javax.swing.JTabbedPane TPlayshist;
    // End of variables declaration//GEN-END:variables
}
